### ISSUE TITLE
wario_walking.gb won't start (waiting for GL)

### ISSUE THREAD

**Issue by ghost** [krocki/gb#4]
Emulator gets stuck with the following output:

    $ LD_LIBRARY_PATH=. ./gameboy wario_walking.gb
    BOOTROM=0
    DEBUG=0
    SPEED_LIMIT=1
    STDOUT=0
        0.000, GB starting...
        0.000, reset ok, waiting for GL...

**Comment by krocki** [comment]
I would need more information on the OS and GLFW implementation installed - I used GLFW3 on Mac OS up to Mojave and Ubuntu, please make sure you are using GLFW3 or modify the main_lcd.c code accordingly for some other version. The problem indicates that the program gets stuck in Line 167 of main_lcd.c: while (!gl_ok) usleep(10); - which means that gl_ok never gets set to TRUE. It should happen right after the gl window is created in lcd_init(), so I would suspect that the issue is somewhere between lines 97-107 and may be related to opening GLFW window.

**Comment by ghost** [comment]
The problem was that when GLFW is compiled with Wayland support then it disables X11 support, and because I am not running a Wayland session OpenGL initialization failed.
